Přidávám článek o Pyladies Advanced
pyvec/blog.python.cz pull request #16
Opened 2017-01-08 16:45 UTC by zoellenka

Ještě mi tam chybí fotky a odkazy... a poděkování

2017-01-13 20:12 UTC, lspdv commented
@baradrb korektura prosim?

2017-01-14 12:33 UTC, honzajavorek requested changes
Paráda článek! Díky moc! 👍

Našel jsem jen pár drobností, které záleží na tobě, jestli chceš opravovat. Ale to formátování seznamu bychom opravit měli, pokusil jsem se pomoct v komentáři.

2017-01-14 12:33 UTC, honzajavorek commented on content/2017-01-08_pyladies-advanced.md
> + Gravatar: zoelles@gmail.com
Tady je mezera navíc na začátku před slovem `Gravatar`, ale blog se s tím možná popere.

2017-01-14 12:33 UTC, honzajavorek commented on content/2017-01-08_pyladies-advanced.md
> +Od července do půle října 2016 probíhaly různě po Praze v kavárnách, posléze, díky Oskarovi,  v coworkingové zasedačce [Usertech](https://usertechnologies.com/) na Smíchově. Což je super prostor! Děk
Trochu mi v té první větě chybí podmět - kdo/co probíhaly. Já vím, že to je v nadpisu, ale stejně.

2017-01-14 12:33 UTC, honzajavorek commented on content/2017-01-08_pyladies-advanced.md
> +
Ten blok se seznamem potřebuje trochu přeformátovat - když koukám na [náhled na GitHubu](https://github.com/zoellenka/blog.python.cz/blob/241afd287d088705b0406d12d0658ce320d47b31/content/2017-01-08_pyladies-advanced.md), Markdown si s tím neporadil. Tohle je obtížné i pro ostřílené Markdownové kovboje, tak s tím zkusím pomoct:

```
Celkem proběhlo 22 těchto setkání, které vždy svolala nejlepší organizátorka Veronička. Pyladies Advanced bylo maloformátové setkání, nejvíce nás přišlo asi 12, někdy dorazilo i více koučů než Pyladies, ale umožnilo nám to:

1.  posunout se dále v tom, co děláme. Často jsme díky pomoci koučů vyřešily problém s chybami, na které bychom samy došly jen těžko. Bylo nám vysvětleno spoustu nových témat, jako např. regulární výrazy.  Na tohle na kurzech většinou nezbývá čas a správné programátorce se to hodí znát!

    Materiálů je na internetu sice spousta, ale člověk se snadno zamotá. 

2.  Některá setkání byla více networkingového rázu typu meetup než programming session. Ale to nám zase umožnilo zapojit se aktivněji do Python komunity v ČR. Mohly jsme plánovat další kurzy pro budoucí Pyladies, podívat se na Pycon, zapojit se do psaní atd. 

Na dvou Pyladies Advanced se objevila i zahraniční Pyladie, což je strašně super, že se tato mezinárodní komunita sdružuje.
```

Výsledek:

------

Celkem proběhlo 22 těchto setkání, které vždy svolala nejlepší organizátorka Veronička. Pyladies Advanced bylo maloformátové setkání, nejvíce nás přišlo asi 12, někdy dorazilo i více koučů než Pyladies, ale umožnilo nám to:

1.  posunout se dále v tom, co děláme. Často jsme díky pomoci koučů vyřešily problém s chybami, na které bychom samy došly jen těžko. Bylo nám vysvětleno spoustu nových témat, jako např. regulární výrazy.  Na tohle na kurzech většinou nezbývá čas a správné programátorce se to hodí znát!

    Materiálů je na internetu sice spousta, ale člověk se snadno zamotá. 

2.  Některá setkání byla více networkingového rázu typu meetup než programming session. Ale to nám zase umožnilo zapojit se aktivněji do Python komunity v ČR. Mohly jsme plánovat další kurzy pro budoucí Pyladies, podívat se na Pycon, zapojit se do psaní atd. 

Na dvou Pyladies Advanced se objevila i zahraniční Pyladie, což je strašně super, že se tato mezinárodní komunita sdružuje.

2017-01-14 12:33 UTC, honzajavorek commented on content/2017-01-08_pyladies-advanced.md
> +Na dvou Pyladies Advanced se objevila i zahraniční Pyladie, což je strašně super, že se tato mezinárodní komunita sdružuje.
```diff
- Pyladie
+ Pylady
```

Nebo možná i PyLady (velké L)?

2017-01-15 17:25 UTC, baradrb commented on content/2017-01-08_pyladies-advanced.md
> +Od července do půle října 2016 probíhaly různě po Praze v kavárnách, posléze, díky Oskarovi,  v coworkingové zasedačce [Usertech](https://usertechnologies.com/) na Smíchově. Což je super prostor! Děk
Zoe místo Zou?
Zoe je holka, která se učí Python.
Od července do půlky října ... (přidat ten podmět) ... díky Oskarovi, TADY JSOU DVĚ MEZERY v ...

2017-01-15 17:25 UTC, baradrb commented on content/2017-01-08_pyladies-advanced.md
> +1) posunout se dále v tom, co děláme. Často jsme díky pomoci koučů vyřešily problém s chybami, na které bychom samy došly jen těžko. Bylo nám vysvětleno spoustu nových témat, jako např. regulární výr
... na které bychom samy přišly jen těžko.
... výrazay. ZASE DVĚ MEZERY
... a správné programátorce se to hodí! NEBO ... správná programátorka by to měla znát!

2017-01-15 17:25 UTC, baradrb commented on content/2017-01-08_pyladies-advanced.md
> +2) Některá setkání byla více networkingového rázu typu meetup než programming session. Ale to nám zase umožnilo zapojit se aktivněji do Python komunity v ČR. Mohly jsme plánovat další kurzy pro budou
... PyCon CZ, 
... zapojit se do psaní ČEHO?

2017-01-15 17:25 UTC, baradrb commented on content/2017-01-08_pyladies-advanced.md
> +Na dvou Pyladies Advanced se objevila i zahraniční Pyladie, což je strašně super, že se tato mezinárodní komunita sdružuje.
... Pylady. Je skvělé, že se komunita rozšiřuje i mezinárodně.
(taky nevím s tím L - měli bychom to nějak sjednotit už navždy, taky to míchám :))

2017-01-15 17:25 UTC, baradrb commented on content/2017-01-08_pyladies-advanced.md
> +Osobně jsem se snažila skoro žádné setkání Pyladies Advanced nezmeškat, i když ne vždy se mi to povedlo, protože to byla super akce, kde bylo vidět, jak se člověk posunuje v programování dále a učí s
I když se mi to ne vždy povedlo, snažila jsem se setkání Pyladies Advanced nezmeškat, protože to byly výborné akce, kde ...

2017-01-15 17:25 UTC, baradrb commented on content/2017-01-08_pyladies-advanced.md
> +A v neposlední řadě. S Pyladies je prostě sranda. Někdy jsme se tak nasmály, že to ani nešlo :)
A v neposlední řadě: s Pyladies je prostě sranda. 
Té další větě nerozumím: co nešlo?

2017-01-15 18:03 UTC, honzajavorek commented on content/2017-01-08_pyladies-advanced.md
> +A v neposlední řadě. S Pyladies je prostě sranda. Někdy jsme se tak nasmály, že to ani nešlo :)
To se tak říká, že to bylo tak moc, že to ani nešlo :)

2017-01-15 18:04 UTC, honzajavorek commented on content/2017-01-08_pyladies-advanced.md
> +Na dvou Pyladies Advanced se objevila i zahraniční Pyladie, což je strašně super, že se tato mezinárodní komunita sdružuje.
Když jdu na http://www.pyladies.com/, tak tam mají všude velké L.

2017-01-16 09:03 UTC, encukou commented
@zoellenka Jestli chceš, můžu ti ten text opravit já podle připomínek, co tu lidi mají. Stačí říct.

2017-02-17 09:57 UTC, zoellenka commented
Jeee, díky, já jsem si nějak vůbec nevšimla, že se tu diskutuje. Každopádně děkuji. Zou můžete nechat asi tak... 
Psaní blogu, článků a občas i revize materiálů. Myslela jsem tím, že se můžeš zapojit do přípravy, když chceš. 

Text upravit zvládnu, ale nemůžu tam dostat fotky...

2017-02-17 10:23 UTC, encukou commented
Na fotky napiš odkazy, nebo mi je pošli mailem (encukou@gmail.com).

2017-02-18 10:00 UTC, lspdv commented
fotky mam asi spis ja. poslu

2017-02-20 19:02 UTC, encukou commented
Fotky jsem přidal do https://github.com/zoellenka/blog.python.cz/pull/1

2017-05-28 20:13 UTC, honzajavorek commented
Co muzu udelat pro to, abychom tohle dotahli do konce?

2017-05-28 21:07 UTC, lspdv commented
To je jednoduche. Uz pred nekolika mesici jsme prosily o review a merge. :-)

2017-05-28 22:13 GMT+02:00 Honza Javorek <notifications@github.com>:

> Co muzu udelat pro to, abychom tohle dotahli do konce?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pyvec/blog.python.cz/pull/16#issuecomment-304537414>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AL5Lbaqqbn4H_RfpBGfZyAOVnlTZyPDeks5r-dV2gaJpZM4Ldu78>
> .
>

2017-05-29 09:29 UTC, honzajavorek commented
Jednoduché to není, protože review je udělané, jsou navržené změny, fotky jsou v PR na repozitář od @zoellenka (https://github.com/zoellenka/blog.python.cz/pull/1), atd. Takže review proběhlo, teď by se měly zapracovat změny, a potom to můžeme mergnout. Ale k tomu prostřednímu bodu několik měsíců nedochází, takže se to tady snažím připomenout a oživit.

2017-05-29 09:33 UTC, lspdv commented
Tak v tom pripade pro to asi muzes udelat to, ze napises primo Lence a
pripomenes ji to. Lenka predpokladam na Github bezne nechodi a nemusi mit
nastavene notifikace
po 29. 5. 2017 v 11:29 odesílatel Honza Javorek <notifications@github.com>
napsal:

> Jednoduché to není, protože review je udělané, jsou navržené změny, fotky
> jsou v PR na repozitář od @zoellenka <https://github.com/zoellenka> (
> zoellenka#1 <https://github.com/zoellenka/blog.python.cz/pull/1>), atd.
> Takže review proběhlo, teď by se měly zapracovat změny, a potom to můžeme
> mergnout. Ale k tomu prostřednímu bodu několik měsíců nedochází, takže se
> to tady snažím připomenout a oživit.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pyvec/blog.python.cz/pull/16#issuecomment-304617049>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AL5LbToX4BkXkHMi4jXjgsLZtxIjBaWXks5r-o_ugaJpZM4Ldu78>
> .
>

2017-05-30 20:20 UTC, zoellenka commented
Ahoj, je to tak, mám vypnuté notifikace, chodilo mi jich strašně moc a většina nebyla na mě. Momentálně vůbec nevím, kde co s tím mám udělat. Ideální by bylo, kdyby někdo mohl do článku doplnit fotky a vypublikovat ho. Jestli mám udělat něco konkrétního, prosím o navigaci přes slack, nemůžu ten článek nějak najít... a moc se omlouvám, jsem opravdu hrozná - normálně se na GitHubu docela vyznám, ale teďka jsem ztracená...

2017-06-02 09:07 UTC, honzajavorek commented
Domluvili jsme se s Lenkou, že to spolu dotáhneme na PyCon CZ.

2017-06-02 09:11 UTC, lspdv commented
Ok, fotky jsem vam tusim uz davala, ale pokud by vam chybely, dejte mi
vedet, pripadne tam budu take, tak udelame rychlo akci.

Dne 2. června 2017 11:07 Honza Javorek <notifications@github.com> napsal(a):

> Domluvili jsme se s Lenkou, že to spolu dotáhneme na PyCon CZ.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pyvec/blog.python.cz/pull/16#issuecomment-305732859>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AL5LbZmTH6gy-cCGIR1uIZwl4b4hmvJEks5r_9DPgaJpZM4Ldu78>
> .
>

2017-06-10 14:36 UTC, honzajavorek approved these changes

2017-06-10 14:37 UTC, merged

2017-06-10 14:37 UTC, honzajavorek commented
Díky moc!